=== alexgorbatchev/dmx-lights/tools/ofl/schemas/fixture.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/OpenLightingProject/open-fixture-library/master/schemas/fixture.json",

  "version": "12.5.1",

  "type": "object",
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/OpenLightingProject/open-fixture-library/master/schemas/fixture.json"
    },
    "name": {
      "description": "unique in manufacturer",
      "$ref": "definitions.json#/nonEmptyString"
    },
    "shortName": {
      "description": "unique globally; if not set: use name",
      "$ref": "definitions.json#/nonEmptyString"
    },
    "categories": {
      "type": "array",
      "description": "most important category first",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "enum": [
          "Barrel Scanner",
          "Blinder",
          "Color Changer",
          "Dimmer",
          "Effect",
          "Fan",
          "Flower",
          "Hazer",
          "Laser",
          "Matrix",
          "Moving Head",
          "Pixel Bar",
          "Scanner",
          "Smoke",
          "Stand",
          "Strobe",
          "Other"
        ]
      }
    },
    "meta": {
      "type": "object",
      "properties": {
        "authors": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": { "$ref": "definitions.json#/nonEmptyString" }
        },
        "createDate": { "$ref": "definitions.json#/isoDateString" },
        "lastModifyDate": { "$ref": "definitions.json#/isoDateString" },
        "importPlugin": {
          "type": "object",
          "properties": {
            "plugin": { "$ref": "definitions.json#/nonEmptyString" },
            "date": { "$ref": "definitions.json#/isoDateString" },
            "comment": { "$ref": "definitions.json#/nonEmptyMultilineString" }
          },
          "required": ["plugin", "date"],
          "additionalProperties": false
        }
      },
      "required": ["authors", "createDate", "lastModifyDate"],
      "additionalProperties": false
    },
    "comment": { "$ref": "definitions.json#/nonEmptyMultilineString" },
    "links": {
      "type": "object",
      "properties": {
        "manual": { "$ref": "definitions.json#/urlArray" },
        "productPage": { "$ref": "definitions.json#/urlArray" },
        "video": { "$ref": "definitions.json#/urlArray" },
        "other": { "$ref": "definitions.json#/urlArray" }
      },
      "anyOf": [
        { "required": ["manual"] },
        { "required": ["productPage"] },
        { "required": ["video"] },
        { "required": ["other"] }
      ],
      "additionalProperties": false
    },
    "helpWanted": { "$ref": "definitions.json#/nonEmptyString" },
    "rdm": {
      "type": "object",
      "properties": {
        "modelId": {
          "type": "integer",
          "minimum": 0,
          "maximum": 65535
        },
        "softwareVersion": { "$ref": "definitions.json#/nonEmptyString" }
      },
      "required": ["modelId"],
      "additionalProperties": false
    },
    "physical": {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "dimensions": {
          "$ref": "definitions.json#/dimensionsXYZ"
        },
        "weight": {
          "description": "in kg",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "power": {
          "description": "in W",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "powerConnectors": {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "properties": {
            "IEC C13": {
              "$ref": "definitions.json#/powerConnectorType"
            },
            "IEC C19": {
              "type": "string",
              "const": "input only"
            },
            "powerCON": {
              "$ref": "definitions.json#/powerConnectorType"
            },
            "powerCON TRUE1": {
              "$ref": "definitions.json#/powerConnectorType"
            },
            "powerCON TRUE1 TOP": {
              "$ref": "definitions.json#/powerConnectorType"
            },
            "powerCON 32 A": {
              "type": "string",
              "const": "input only"
            },
            "Hardwired": {
              "$ref": "definitions.json#/powerConnectorType"
            },
            "Proprietary": {
              "$ref": "definitions.json#/powerConnectorType"
            }
          }
        },
        "DMXconnector": {
          "$comment": "additions are welcome",
          "enum": [
            "3-pin",
            "3-pin (swapped +/-)",
            "3-pin XLR IP65",
            "5-pin",
            "5-pin XLR IP65",
            "3-pin and 5-pin",
            "3.5mm stereo jack",
            "RJ45"
          ]
        },
        "bulb": {
          "type": "object",
          "minProperties": 1,
          "properties": {
            "type": {
              "description": "e.g. 'LED'",
              "$ref": "definitions.json#/nonEmptyString"
            },
            "colorTemperature": {
              "description": "in K",
              "type": "number",
              "exclusiveMinimum": 0
            },
            "lumens": {
              "type": "number",
              "exclusiveMinimum": 0
            }
          },
          "additionalProperties": false
        },
        "lens": {
          "type": "object",
          "minProperties": 1,
          "properties": {
            "name": {
              "description": "e.g. 'PC', 'Fresnel'",
              "$ref": "definitions.json#/nonEmptyString"
            },
            "degreesMinMax": {
              "type": "array",
              "minItems": 2,
              "maxItems": 2,
              "items": {
                "type": "number",
                "minimum": 0,
                "maximum": 360
              }
            }
          },
          "additionalProperties": false
        },
        "matrixPixels": {
          "type": "object",
          "minProperties": 1,
          "properties": {
            "dimensions": { "$ref": "definitions.json#/dimensionsXYZ" },
            "spacing": { "$ref": "definitions.json#/dimensionsXYZ" }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "matrix": { "$ref": "matrix.json#" },
    "wheels": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$comment": "wheel names",
        "$ref": "definitions.json#/nonEmptyString"
      },
      "additionalProperties": {
        "type": "object",
        "properties": {
          "direction": { "enum": ["CW", "CCW"] },
          "slots": {
            "type": "array",
            "minItems": 2,
            "items": { "$ref": "wheel-slot.json#" }
          }
        },
        "required": ["slots"],
        "additionalProperties": false
      }
    },
    "availableChannels": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$comment": "channel keys",
        "$ref": "definitions.json#/noVariablesString"
      },
      "additionalProperties": { "$ref": "channel.json#" }
    },
    "templateChannels": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$comment": "template channel keys",
        "$ref": "definitions.json#/variablePixelKeyString"
      },
      "additionalProperties": { "$ref": "channel.json#" }
    },
    "modes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": { "$ref": "definitions.json#/modeNameString" },
          "shortName": { "$ref": "definitions.json#/modeNameString" },
          "rdmPersonalityIndex": {
            "type": "integer",
            "minimum": 1
          },
          "physical": { "$ref": "#/properties/physical" },
          "channels": {
            "type": "array",
            "minItems": 1,
            "items": {
              "oneOf": [
                {
                  "$comment": "for unused channels",
                  "type": "null"
                },
                {
                  "$comment": "normal channel keys, resolved template channel keys or channel alias keys",
                  "$ref": "definitions.json#/noVariablesString"
                },
                {
                  "$comment": "matrix channel insert block",
                  "type": "object",
                  "properties": {
                    "insert": { "const": "matrixChannels" },
                    "repeatFor": {
                      "oneOf": [
                        {
                          "enum": [
                            "eachPixelABC",
                            "eachPixelXYZ",
                            "eachPixelXZY",
                            "eachPixelYXZ",
                            "eachPixelYZX",
                            "eachPixelZXY",
                            "eachPixelZYX",
                            "eachPixelGroup"
                          ]
                        },
                        {
                          "type": "array",
                          "minItems": 1,
                          "uniqueItems": true,
                          "items": {
                            "$comment": "pixel key or pixel group key",
                            "$ref": "definitions.json#/noVariablesString"
                          }
                        }
                      ]
                    },
                    "channelOrder": { "enum": ["perPixel", "perChannel"] },
                    "templateChannels": {
                      "type": "array",
                      "minItems": 1,
                      "items": {
                        "oneOf": [
                          {
                            "$comment": "for unused channels",
                            "type": "null"
                          },
                          {
                            "$comment": "template channel key or template channel alias key",
                            "$ref": "definitions.json#/variablePixelKeyString"
                          }
                        ]
                      }
                    }
                  },
                  "required": ["insert", "repeatFor", "channelOrder", "templateChannels"],
                  "additionalProperties": false
                }
              ]
            }
          }
        },
        "required": ["name", "channels"],
        "additionalProperties": false
      }
    }
  },
  "dependentRequired": {
    "matrix": ["templateChannels"],
    "templateChannels": ["matrix"]
  },
  "required": ["$schema", "name", "categories", "meta", "modes"],
  "allOf": [
    {
      "if": {
        "properties": { "modes": { "contains": { "required": ["rdmPersonalityIndex"] } } }
      },
      "then": {
        "required": ["rdm"]
      }
    },
    {
      "anyOf": [
        { "required": ["availableChannels"] },
        { "required": ["templateChannels"] }
      ]
    }
  ],
  "additionalProperties": false
}

=== alexgorbatchev/dmx-lights/tools/ofl/fixtures/alex/rgbw-spot-light.json
{
  "$schema": "https://raw.githubusercontent.com/OpenLightingProject/open-fixture-library/master/schemas/fixture.json",
  "name": "RGBW Spot Light",
  "categories": ["Color Changer", "Strobe", "Effect"],
  "meta": {
    "authors": ["Alex"],
    "createDate": "2026-07-13",
    "lastModifyDate": "2026-07-13"
  },
  "physical": {
    "dimensions": [150, 150, 65],
    "DMXconnector": "3-pin",
    "bulb": {
      "type": "LED"
    }
  },
  "availableChannels": {
    "Master Control": {
      "capabilities": [
        { "dmxRange": [0, 8], "type": "NoFunction" },
        { "dmxRange": [9, 134], "type": "Intensity", "brightnessStart": "0%", "brightnessEnd": "100%", "comment": "Red green blue white light from dark to bright" },
        { "dmxRange": [135, 239], "type": "ShutterStrobe", "shutterEffect": "Strobe", "speedStart": "slow", "speedEnd": "fast" },
        { "dmxRange": [240, 255], "type": "Effect", "effectName": "Ch2-ch5 effect" }
      ]
    },
    "Red": {
      "capabilities": [
        { "dmxRange": [0, 0], "type": "ColorIntensity", "color": "Red", "brightness": "0%", "comment": "Red light keeps dark" },
        { "dmxRange": [1, 255], "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%", "comment": "Red light from dark to bright" }
      ]
    },
    "Green": {
      "capabilities": [
        { "dmxRange": [0, 0], "type": "ColorIntensity", "color": "Green", "brightness": "0%", "comment": "green light keeps dark" },
        { "dmxRange": [1, 255], "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%", "comment": "green light from dark to bright" }
      ]
    },
    "Blue": {
      "capabilities": [
        { "dmxRange": [0, 0], "type": "ColorIntensity", "color": "Blue", "brightness": "0%", "comment": "blue light keeps dark" },
        { "dmxRange": [1, 255], "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%", "comment": "blue light from dark to bright" }
      ]
    },
    "White": {
      "capabilities": [
        { "dmxRange": [0, 0], "type": "ColorIntensity", "color": "White", "brightness": "0%", "comment": "white light keeps dark" },
        { "dmxRange": [1, 255], "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%", "comment": "white light from dark to bright" }
      ]
    },
    "Effect Mode": {
      "capabilities": [
        { "dmxRange": [0, 2], "type": "NoFunction" },
        { "dmxRange": [3, 31], "type": "Effect", "effectName": "red, green, blue, white jump change" },
        { "dmxRange": [32, 63], "type": "Effect", "effectName": "red static, green, blue, white jump change" },
        { "dmxRange": [64, 79], "type": "Effect", "effectName": "green static, red, blue, white jump change" },
        { "dmxRange": [80, 95], "type": "Effect", "effectName": "blue static, red, green, white jump change" },
        { "dmxRange": [96, 111], "type": "Effect", "effectName": "white static, red, green, blue jump change" },
        { "dmxRange": [112, 143], "type": "Effect", "effectName": "red, green, blue, white gradual change, speed slow" },
        { "dmxRange": [144, 159], "type": "Effect", "effectName": "red, green, gradual change, speed fast" },
        { "dmxRange": [160, 175], "type": "Effect", "effectName": "red, blue, gradual change, green white close" },
        { "dmxRange": [176, 191], "type": "Effect", "effectName": "Green blue gradual change, red white close" },
        { "dmxRange": [192, 207], "type": "Effect", "effectName": "red, green, blue gradual change" },
        { "dmxRange": [208, 223], "type": "Effect", "effectName": "red, green, blue white jump change" },
        { "dmxRange": [224, 239], "type": "Effect", "effectName": "Sound 1 Change color and strobe", "soundControlled": true },
        { "dmxRange": [240, 249], "type": "Effect", "effectName": "Sound 2 Change colors with sound", "soundControlled": true },
        { "dmxRange": [250, 255], "type": "Effect", "effectName": "Sound 3 Change colors and flicker with sound", "soundControlled": true }
      ]
    }
  },
  "modes": [
    {
      "name": "6 Channel",
      "shortName": "6ch",
      "channels": [
        "Master Control",
        "Red",
        "Green",
        "Blue",
        "White",
        "Effect Mode"
      ]
    }
  ]
}

=== alexgorbatchev/dmx-lights/tools/ofl/fixtures/armor/plus-bee-beam-moving-head.json
{
  "$schema": "https://raw.githubusercontent.com/OpenLightingProject/open-fixture-library/master/schemas/fixture.json",
  "name": "Plus Bee Beam Moving Head Light",
  "categories": ["Moving Head", "Color Changer", "Effect"],
  "meta": {
    "authors": ["Alex"],
    "createDate": "2024-01-01",
    "lastModifyDate": "2024-01-01"
  },
  "physical": {
    "DMXconnector": "3-pin",
    "bulb": {
      "type": "LED"
    }
  },
  "availableChannels": {
    "X Motor": {
      "capability": { "type": "Pan", "angleStart": "0deg", "angleEnd": "540deg" }
    },
    "X Motor Speed": {
      "capability": { "type": "PanTiltSpeed", "speedStart": "fast", "speedEnd": "slow" }
    },
    "X Motor Slip ring": {
      "capabilities": [
        { "dmxRange": [0, 9], "type": "NoFunction" },
        { "dmxRange": [10, 127], "type": "PanContinuous", "speedStart": "slow CW", "speedEnd": "fast CW" },
        { "dmxRange": [128, 255], "type": "PanContinuous", "speedStart": "fast CCW", "speedEnd": "slow CCW" }
      ]
    },
    "Bee eyes rotation": {
      "capabilities": [
        { "dmxRange": [0, 128], "type": "Rotation", "angleStart": "0deg", "angleEnd": "180deg" },
        { "dmxRange": [129, 191], "type": "Rotation", "speedStart": "slow CW", "speedEnd": "fast CW" },
        { "dmxRange": [192, 255], "type": "Rotation", "speedStart": "slow CCW", "speedEnd": "fast CCW" }
      ]
    },
    "Y-axis 1": {
      "capability": { "type": "Tilt", "angleStart": "0deg", "angleEnd": "90deg" }
    },
    "Y-axis 2": {
      "capability": { "type": "Tilt", "angleStart": "0deg", "angleEnd": "90deg" }
    },
    "Y-axis 3": {
      "capability": { "type": "Tilt", "angleStart": "0deg", "angleEnd": "90deg" }
    },
    "Dimmer": {
      "capability": { "type": "Intensity", "brightnessStart": "0%", "brightnessEnd": "100%" }
    },
    "STROB": {
      "capabilities": [
        { "dmxRange": [0, 10], "type": "ShutterStrobe", "shutterEffect": "Open" },
        { "dmxRange": [11, 255], "type": "ShutterStrobe", "shutterEffect": "Strobe", "speedStart": "slow", "speedEnd": "fast" }
      ]
    },
    "Beam-red": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam-green": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam-blue": { "capability": { "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam-white": { "capability": { "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee-red": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee-green": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee-blue": { "capability": { "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee-white": { "capability": { "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    
    "Red Laser": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Green Laser": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    
    "STROB1": {
      "capabilities": [
        { "dmxRange": [0, 10], "type": "ShutterStrobe", "shutterEffect": "Open" },
        { "dmxRange": [11, 255], "type": "ShutterStrobe", "shutterEffect": "Strobe", "speedStart": "slow", "speedEnd": "fast" }
      ]
    },
    "STROB2": {
      "capabilities": [
        { "dmxRange": [0, 10], "type": "ShutterStrobe", "shutterEffect": "Open" },
        { "dmxRange": [11, 255], "type": "ShutterStrobe", "shutterEffect": "Strobe", "speedStart": "slow", "speedEnd": "fast" }
      ]
    },
    "Light Belt": {
      "capabilities": [
        { "dmxRange": [0, 9], "type": "NoFunction" },
        { "dmxRange": [10, 255], "type": "Effect", "effectName": "Change effect every 10 seconds" }
      ]
    },
    "Light Belt Speed": {
      "capability": { "type": "EffectSpeed", "speedStart": "slow", "speedEnd": "fast" }
    },
    "Macro function 24ch": {
      "capabilities": [
        { "dmxRange": [0, 50], "type": "Effect", "effectName": "Channel 1 to Channel 23 Active" },
        { "dmxRange": [51, 150], "type": "Effect", "effectName": "Auto run" },
        { "dmxRange": [151, 250], "type": "Effect", "effectName": "Voice mode", "soundControlled": true },
        { "dmxRange": [251, 255], "type": "Maintenance", "comment": "3 second reset", "hold": "3s" }
      ]
    },

    "Beam1-Red": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam1-Green": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam1-Blue": { "capability": { "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam1-White": { "capability": { "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam2-Red": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam2-Green": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam2-Blue": { "capability": { "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam2-White": { "capability": { "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam3-Red": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam3-Green": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam3-Blue": { "capability": { "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Beam3-White": { "capability": { "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee4-Red": { "capability": { "type": "ColorIntensity", "color": "Red", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee4-Green": { "capability": { "type": "ColorIntensity", "color": "Green", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee4-Blue": { "capability": { "type": "ColorIntensity", "color": "Blue", "brightnessStart": "0%", "brightnessEnd": "100%" } },
    "Bee4-White": { "capability": { "type": "ColorIntensity", "color": "White", "brightnessStart": "0%", "brightnessEnd": "100%" } },

    "Yellow Strobe": {
      "capabilities": [
        { "dmxRange": [0, 10], "type": "ShutterStrobe", "shutterEffect": "Open" },
        { "dmxRange": [11, 255], "type": "ShutterStrobe", "shutterEffect": "Strobe", "speedStart": "slow", "speedEnd": "fast", "comment": "Yellow Strobe" }
      ]
    },
    "White Strobe": {
      "capabilities": [
        { "dmxRange": [0, 10], "type": "ShutterStrobe", "shutterEffect": "Open" },
        { "dmxRange": [11, 255], "type": "ShutterStrobe", "shutterEffect": "Strobe", "speedStart": "slow", "speedEnd": "fast", "comment": "White Strobe" }
      ]
    },
    "Macro function 32ch": {
      "capabilities": [
        { "dmxRange": [0, 50], "type": "Effect", "effectName": "Channel 1 to Channel 31 Active" },
        { "dmxRange": [51, 149], "type": "Effect", "effectName": "Auto run" },
        { "dmxRange": [150, 250], "type": "Effect", "effectName": "Voice mode", "soundControlled": true },
        { "dmxRange": [251, 255], "type": "Maintenance", "comment": "3 second reset", "hold": "3s" }
      ]
    }
  },
  "modes": [
    {
      "name": "24 Channel",
      "shortName": "24ch",
      "channels": [
        "X Motor",
        "X Motor Speed",
        "X Motor Slip ring",
        "Bee eyes rotation",
        "Y-axis 1",
        "Y-axis 2",
        "Y-axis 3",
        "Dimmer",
        "STROB",
        "Beam-red",
        "Beam-green",
        "Beam-blue",
        "Beam-white",
        "Bee-red",
        "Bee-green",
        "Bee-blue",
        "Bee-white",
        "Red Laser",
        "Green Laser",
        "STROB1",
        "STROB2",
        "Light Belt",
        "Light Belt Speed",
        "Macro function 24ch"
      ]
    },
    {
      "name": "32 Channel",
      "shortName": "32ch",
      "channels": [
        "X Motor",
        "X Motor Speed",
        "X Motor Slip ring",
        "Bee eyes rotation",
        "Y-axis 1",
        "Y-axis 2",
        "Y-axis 3",
        "Dimmer",
        "STROB",
        "Beam1-Red",
        "Beam1-Green",
        "Beam1-Blue",
        "Beam1-White",
        "Beam2-Red",
        "Beam2-Green",
        "Beam2-Blue",
        "Beam2-White",
        "Beam3-Red",
        "Beam3-Green",
        "Beam3-Blue",
        "Beam3-White",
        "Bee4-Red",
        "Bee4-Green",
        "Bee4-Blue",
        "Bee4-White",
        "Red Laser",
        "Green Laser",
        "Yellow Strobe",
        "White Strobe",
        "Light Belt",
        "Light Belt Speed",
        "Macro function 32ch"
      ]
    }
  ]
}
